# Generated by Django 4.1.2 on 2022-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="item_pics")),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
