# Generated by Django 4.1.2 on 2022-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items", name="desc", field=models.TextField(default="*item*"),
        ),
        migrations.AddField(
            model_name="items",
            name="num",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.ImageField(default="*item*", upload_to="item_pics"),
        ),
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(default="*name*", max_length=100),
        ),
        migrations.AlterField(
            model_name="items",
            name="type",
            field=models.CharField(default="*item*", max_length=100),
        ),
    ]
